### ISSUE TITLE
plex-rich-presence DOCKER builds for Synology (and more?)

### ISSUE THREAD

**Issue by FloydianSound** [Ombrelin/plex-rich-presence#102]
I would love to see this as a docker app

i'm on Synology DSM224+ (DSM7.2) (Linux)
we use the Package Manager and Container Manager (Docker-compose2 basically)

any plans to make a release for this ? would love to uncouple this plug-in from my PC if possible.

**Comment by Ombrelin** [comment]
Duplicate of #56
