### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by Ombrelin** [Ombrelin/plex-rich-presence#17]

**Comment by Soitora** [comment]
Would be nice if it could get added to the official [Windows Package Manager](https://github.com/microsoft/winget-cli)'s  [community repository](https://github.com/microsoft/winget-pkgs)

Winget is currently in early stages but it's already looking super promising with a clear roadmap

**Comment by Ombrelin** [comment]
Never done that, but I'll look into it eventually !

**Comment by Ombrelin** [comment]
@Soitora The chocolatey package is still pending review but the winget package is published ! 
![image](https://user-images.githubusercontent.com/47502331/110185114-cfc0e080-7e11-11eb-853f-026690911ac5.png)

**Comment by Soitora** [comment]
> @Soitora The chocolatey package is still pending review but the winget package is published ! 
> ![image](https://user-images.githubusercontent.com/47502331/110185114-cfc0e080-7e11-11eb-853f-026690911ac5.png)
> 

Awesome ! 👍

**Comment by Ombrelin** [comment]
Won't implement, as it is available for windows through winget : https://winget.run/pkg/Ombrelin/PlexRichPresence
