### ISSUE TITLE
Problem building. Release a version?

### ISSUE THREAD

**Issue by danielpmc** [Ombrelin/plex-rich-presence#2]
Hello, Im having a problem building this. Could you send me a built version please?

**Comment by Ombrelin** [comment]
Hello !

thank you for your interest in my project ! 
The project is built using maven, I will provide a guide to build as long as a release version as soon as possible.

**Comment by danielpmc** [comment]
Ok thanks!

**Comment by Ombrelin** [comment]
I juste provided a github release and create a readme with project description and build instructions.
Feel free to open another issue if you experience trouble with provided material.
