### ISSUE TITLE
Add version tag in application

### ISSUE THREAD

**Issue by LacazeThomas** [Ombrelin/plex-rich-presence#21]
Hi, 
It's possible to add version information in main view, or in logs ?
![javaw_8fLIHHLOqM](https://user-images.githubusercontent.com/19855907/106506264-c61e2300-64c9-11eb-96c3-34d6aefb2bd4.png)

**Comment by Ombrelin** [comment]
Totaly doable.
Will implement in next release using https://stackoverflow.com/questions/3697449/retrieve-version-from-maven-pom-xml-in-code
