### ISSUE TITLE
Error occured when connection to discord RPC 

### ISSUE THREAD

**Issue by LacazeThomas** [Ombrelin/plex-rich-presence#23]
Hi,

After upgrading the application in 1.4, Discord can't see Plex-rich-presence. If I rollback to 1.3 this bug doesn't appear.
![javaw_JCvMIzrxAN](https://user-images.githubusercontent.com/19855907/106507101-dedb0880-64ca-11eb-8e1c-c4f9d842ccfe.png)

**Comment by mclarence** [comment]
I have fixed this issue.

I will ensure next time that the error message shows.
