### ISSUE TITLE
ERROR - Initialization failed : Invalid URL host: ""

### ISSUE THREAD

**Issue by KieranRobson** [Ombrelin/plex-rich-presence#27]
INFO  - Logging in
INFO  - Obtaining Plex servers...
INFO  - Successfully logged in as: Kieranr27
ERROR - Initialization failed : Invalid URL host: ""

Hi I keep getting this error, Thanks!

**Comment by Ombrelin** [comment]
Hello !

Sorry to hear that, could you try with [this JAR](https://github.com/Ombrelin/plex-rich-presence/files/5924046/plex-rich-presence-1.4.zip) which feature more precise logging and post the logs here in order to pinpoint the source of the problem ?

**Comment by KieranRobson** [comment]
Hi,

Just wondering how I activate / where i put `java -jar plex-rich-presence.jar -Dlogging.level.root=DEBUG`

could it be the fact i have managed users within plex? 

Thanks for the quick reply!

**Comment by Ombrelin** [comment]
Just open a terminal in the folder in which you stored the downloaded JAR and execute the given command line.
> could it be the fact I have managed users within plex?
I don't have any clue for now, since the PLEX API is kind of a black box we're experiencing with from my point of view x) 
That's why the detailed logs may help us pinpoint the origin of the problem !

**Comment by KieranRobson** [comment]
[debug.txt](https://github.com/Ombrelin/plex-rich-presence/files/6005323/debug.txt)


I hope this is what you mean
Thanks!

**Comment by Ombrelin** [comment]
Look like an issue with the `finalAdress` calculation for one server : 
![image](https://user-images.githubusercontent.com/47502331/108412839-96da1680-722a-11eb-8193-c2951195ee52.png)

**Comment by Ombrelin** [comment]
I'll look into it next week

**Comment by KieranRobson** [comment]
ohh, its looking for 1 but I don't have a server called 1 anymore, I changed servers so it should look for a server called happybox now. But thanks for looking into it, Thanks!

**Comment by KieranRobson** [comment]
Removed old servers from my account and its been fixed! Thanks!

**Comment by Ombrelin** [comment]
Okay nice to hear !
