### ISSUE TITLE
Invalid URL host: ""

### ISSUE THREAD

**Issue by alexthemaster** [Ombrelin/plex-rich-presence#29]
Hello! I have two Plex servers and two users linked to one account on my home server.
After logging in, the error `Initialization failed : Invalid URL host: ""` appears, any ideas why?

![image](https://user-images.githubusercontent.com/31011461/109022970-08034900-76c5-11eb-9fb8-3466394dfa70.png)

**Comment by Ombrelin** [comment]
Hello,
this issue usually happens when you have a server referenced on your plex account but is not active anymore. If you have an old server of yours, please remove it from your plex account and it should work

**Comment by alexthemaster** [comment]
That worked, thank you!
