### ISSUE TITLE
Session not being detected

### ISSUE THREAD

**Issue by danielpmc** [Ombrelin/plex-rich-presence#3]
Hello, 
I downloaded the release (.exe version) and after installing and running it opens a window. asking for a login. i guessed this is my plex login so i entered the info and after i got this:

`Logging in as myemail...
Authentication failed : org.simpleframework.xml.core.PersistenceException: Element 'Server' is already used with @org.simpleframework.xml.Element(name=Server, type=class fr.arsenelapostolet.plexrichpresence.model.Server, data=false, required=false) on field 'Server' private fr.arsenelapostolet.plexrichpresence.model.Server fr.arsenelapostolet.plexrichpresence.model.MediaContainerServer.Server at line 4`

**Comment by Ombrelin** [comment]
Ok, do you have multiple plex servers connected to your plex account ?

**Comment by danielpmc** [comment]
yes i did have. I had some old ones that i didnt remove. Removed them and it worked Thanks!

**Comment by danielpmc** [comment]
Well got it running but my status says `Idling` instead of watching or what ever it should say.

**Comment by Ombrelin** [comment]
Can you share with me the output log in the log feed ?

**Comment by danielpmc** [comment]
![Screenshot](https://user-images.githubusercontent.com/13561350/81478930-443de980-9218-11ea-9791-aa1f7ae20aeb.png)
(Content is playing while taking this screenshot.)

**Comment by Ombrelin** [comment]
Ok it's strange that it's not detecting your plex session. 
I will investigate it, sorry for the inconvenience!

**Comment by danielpmc** [comment]
hey any updates about this?

**Comment by Ombrelin** [comment]
Hi, thank you again for your interest, but I'm currently very busy with school projects, I will get back on this project when I'll have more time. Sorry!

**Comment by danielpmc** [comment]
Ok NP.

**Comment by noah1gamble** [comment]
I am also experiencing this issue.

**Comment by Jackwyz22** [comment]
same here, any updates would be appreciated. Running version 1.21.1.3795

**Comment by ZroNoh** [comment]
Experiencing this issue as well but I only have one server.
