### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by SuperZoops** [Ombrelin/plex-rich-presence#30]
![image](https://user-images.githubusercontent.com/26927890/109048192-13f80680-76d7-11eb-96f0-d37680d66743.png)
![image](https://user-images.githubusercontent.com/26927890/109048205-18bcba80-76d7-11eb-8739-ddaae5cd0316.png)
Both errors pop up after logging in.
Happens with both exe and jar. W10

EDIT: log
```
INFO  - Obtaining Plex servers...
ERROR - Obtain plex server failed : org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.ElementList(entry=Server, data=false, inline=true, name=, type=class fr.arsenelapostolet.plexrichpresence.model.Server, required=true, empty=true) on field 'Server' private java.util.List fr.arsenelapostolet.plexrichpresence.model.MediaContainerServer.Server for class fr.arsenelapostolet.plexrichpresence.model.MediaContainerServer at line 2
ERROR - Initialization failed : org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.ElementList(entry=Server, data=false, inline=true, name=, type=class fr.arsenelapostolet.plexrichpresence.model.Server, required=true, empty=true) on field 'Server' private java.util.List fr.arsenelapostolet.plexrichpresence.model.MediaContainerServer.Server for class fr.arsenelapostolet.plexrichpresence.model.MediaContainerServer at line 2
INFO  - Logging in
ERROR - Initialization failed : org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.ElementList(entry=Server, data=false, inline=true, name=, type=class fr.arsenelapostolet.plexrichpresence.model.Server, required=true, empty=true) on field 'Server' private java.util.List fr.arsenelapostolet.plexrichpresence.model.MediaContainerServer.Server for class fr.arsenelapostolet.plexrichpresence.model.MediaContainerServer at line 2
INFO  - Logging in
ERROR - Initialization failed : org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.ElementList(entry=Server, data=false, inline=true, name=, type=class fr.arsenelapostolet.plexrichpresence.model.Server, required=true, empty=true) on field 'Server' private java.util.List fr.arsenelapostolet.plexrichpresence.model.MediaContainerServer.Server for class fr.arsenelapostolet.plexrichpresence.model.MediaContainerServer at line 2
INFO  - Logging in
ERROR - Initialization failed : org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.ElementList(entry=Server, data=false, inline=true, name=, type=class fr.arsenelapostolet.plexrichpresence.model.Server, required=true, empty=true) on field 'Server' private java.util.List fr.arsenelapostolet.plexrichpresence.model.MediaContainerServer.Server for class fr.arsenelapostolet.plexrichpresence.model.MediaContainerServer at line 2

```

**Comment by mclarence** [comment]
Please follow the steps outlined here

https://github.com/Ombrelin/plex-rich-presence/issues/27#issuecomment-781528469

**Comment by SuperZoops** [comment]
[debugreturn.txt](https://github.com/Ombrelin/plex-rich-presence/files/6039784/debugreturn.txt)
Looks like a different issue.

**Comment by mclarence** [comment]
Did you download the new jar file in the comment linked? The new jar file has more verbose logging.

**Comment by SuperZoops** [comment]
[debugreturn.txt](https://github.com/Ombrelin/plex-rich-presence/files/6039829/debugreturn.txt)
Oh sorry, my bad.

**Comment by mclarence** [comment]
Do you have any plex servers on your account?

**Comment by SuperZoops** [comment]
Just one. Can't find a single trace of any old ones.

**Comment by mclarence** [comment]
Are you the admin/owner of the server?

Can you take a screenshot of this page in plex:
![Screenshot 2021-02-25 120849](https://user-images.githubusercontent.com/25338414/109087815-4e5ab580-7762-11eb-959f-bd001ea52b08.png)

**Comment by SuperZoops** [comment]
![image](https://user-images.githubusercontent.com/26927890/109087896-a5369f80-770e-11eb-865a-ea2172c30d32.png)

**Comment by mclarence** [comment]
Strange.

The issue I am seeing at the moment is that the app is not seeing any plex servers on your account, even though there is one.

Is remote access enabled on the plex server?

**Comment by SuperZoops** [comment]
So this is kind of stupid. Updated the server host, it logged in just fine, no errors. Hurrah.
Not getting actual rpc. But that's one problem solved. Sorry for wasting your time.

**Comment by mclarence** [comment]
All good.

Discord RP will start showing when a stream is detected. It is disabled when there is nothing playing.

**Comment by SuperZoops** [comment]
Well, just tried playing something for maybe 5 minutes, across multiple clients. No luck.
Tried your debug version as well, but it ends at "Successfully logged in as: email."
PRPC window says Logged in and Connected.
Restarted and refreshed Discord multiple times, asked people just in case it's client side, which their API loves.
Getting absolutely nothing. God I love Windows. Let me try restarting.

**Comment by mclarence** [comment]
Please post the logs from the debug jar again.

**Comment by SuperZoops** [comment]
[debugreturn.txt](https://github.com/Ombrelin/plex-rich-presence/files/6039964/debugreturn.txt)
I swear if this is just me being stupid as always.

**Comment by mclarence** [comment]
Externally (outside the LAN) your server can be accessed on port 9669

Internally (inside the LAN) is your server accessed through port 32400 or 9669? If it is the latter then this is probably causing the issue. To see if it fixes the issue, try changing the local port number to 9669. The issue is due to the fact that the plex api only provides the port number without distinguishing if it is the local or external port.

**Comment by SuperZoops** [comment]
Been messing around with ports just now, tried making the 32400 public as well. Both are forwarded, which I don't think matters.
No idea how I can change Plex's internal port.

**Comment by SuperZoops** [comment]
Alright, it was me being stupid. Despite me saying I tried 32400 as public, I only tried unchecking the manual port. Stream detected. Thank you very much for helping me out and sorry for taking so much time off your day. Hope you have a great one.
