### ISSUE TITLE
No RPC shown even though it detects streams

### ISSUE THREAD

**Issue by KNFreed** [Ombrelin/plex-rich-presence#36]
Hello ! I've been trying to use the app (using windows installer) and the RPC isn't showing.

![image](https://user-images.githubusercontent.com/44784500/109629902-a0298400-7b44-11eb-98f9-4d464841a0d6.png)

![image](https://user-images.githubusercontent.com/44784500/109629940-a881bf00-7b44-11eb-8144-d182aa8c2e85.png)
(can't scroll down nor resize the log popup btw, but I think this is gonna be fixed in the next pull request).

![image](https://user-images.githubusercontent.com/44784500/109630073-c818e780-7b44-11eb-8216-6a4f530c9bb8.png)

My RPC isn't shown at boot like #34.

**Comment by mclarence** [comment]
Try restarting the app but make sure discord is open first.

Make sure this is enabled as well.
![image](https://user-images.githubusercontent.com/25338414/109636216-6c2f7c80-7b9f-11eb-9bd1-6d5638899968.png)

**Comment by KNFreed** [comment]
Sorry for the late reply.
Didn't work at first, so I reinstalled it and then everything worked fine. My game display was already on.

Will never know what was wrong with installation :(
