### ISSUE TITLE
Attempt to reconnect after network connection lost.

### ISSUE THREAD

**Issue by mclarence** [Ombrelin/plex-rich-presence#37]
- When network connection is lost, it will show error and user will need to login again. Implement a way to make it reconnect and not show the error message. This is particularly useful when the application is minimised to tray.
- Additional enhancment - clear logs after a specified amount of lines. This is so that the memory will not increase overtime.

**Comment by Ombrelin** [comment]
The app should not be bothered by connection loss for owner at leat.
For non-owners, I expect the websocket client to try to reconnect, but not sure 100% it will work perfectly since I could test is manually.
If issues, please re-open
