### ISSUE TITLE
Not connecting to discord

### ISSUE THREAD

**Issue by CuriousGamerFTW** [Ombrelin/plex-rich-presence#38]
It is not connecting to discord.
https://i.imgur.com/CT7enQz.png

**Comment by mclarence** [comment]
Discord open?

**Comment by CuriousGamerFTW** [comment]
yeah discord is open

**Comment by mclarence** [comment]
Was discord opened BEFORE or AFTER plex rich presence was opened? If it was after, you need to restart plex rich presence. Discord must be opened first before starting plex rich presence.

**Comment by CuriousGamerFTW** [comment]
I restarted the program already

**Comment by CuriousGamerFTW** [comment]
oops

**Comment by mclarence** [comment]
Hmm. Not to sure why its not working.

Can you try reinstalling discord?

**Comment by CuriousGamerFTW** [comment]
Will do

**Comment by CuriousGamerFTW** [comment]
Turns out that fixed it,
Thanks mclarence.
