### ISSUE TITLE
Auto Login not working

### ISSUE THREAD

**Issue by averyfollett** [Ombrelin/plex-rich-presence#39]
Whenever I launch the application, I see 
![image](https://user-images.githubusercontent.com/12211100/110791750-94bf1280-8240-11eb-9d88-b0b534f73d72.png)

If I enable Auto Login before I log in, I still get this screen each time I relaunch and have to manually log in again.

**Comment by Ombrelin** [comment]
So what is your issue ? The autologin is not working ?

**Comment by averyfollett** [comment]
I thought that was obvious. I turn auto login on and the next time I open it does not auto login

**Comment by Ombrelin** [comment]
Please run the app with the `LOG_LEVEL` env variable set to `DEBUG` and post the logs here

**Comment by averyfollett** [comment]
Where do those save to?

**Comment by Ombrelin** [comment]
When you click the export button on the log window you may choose the export location

**Comment by averyfollett** [comment]
This is the startup sequence:

[INFO] Starting application on AVERY-PC with PID 9000 (C:\Program Files (x86)\Plex Rich Presence\plex-rich-presence-1.6.exe started by digit in C:\Program Files (x86)\Plex Rich Presence)
[INFO] No active profile set, falling back to default profiles: default
[INFO] Started application in 0.826 seconds (JVM running for 1.47)
[INFO] Tray icon initialized
[INFO] Logging in
[INFO] Connected to Discord RPC
[INFO] Obtaining Plex servers...
[INFO] Successfully logged in as: dwtech
[INFO] Session acquired for user : Underwater(Underwater) from Kidswaste

**Comment by mclarence** [comment]
Can you please check if the following folder is created:

C:\Users\<your username>\.plexdiscordrp

If it was created can you please check if the folder contains a file called config.properties.

If there is a config.properties. Can you open the file and check if plex.token configuration option is filled in? (Do not post plex token here).

**Comment by averyfollett** [comment]
Weird. It logged in automatically this morning and the token is in that file. Does it only save the token when the application is closed? I think yesterday was the first time I manually closed it instead of just shutting down my computer

**Comment by mclarence** [comment]
Yes, the application will save configuration if it is closed gracefully.

**Comment by averyfollett** [comment]
Okay sweet thanks for the help
