### ISSUE TITLE
Detect Shared Servers

### ISSUE THREAD

**Issue by SebouChu** [Ombrelin/plex-rich-presence#40]
Hello!

I use Plex with a Media Server shared by a friend, but it looks like the application can't detect it. (Searching for servers as owner only, I suppose)

Is there any way to detect them?

Otherwise, seems like you made a good job on this, well done!

**Comment by SebouChu** [comment]
Oh nice, I only find a related issue (#25) after posting this haha, I'll let you close it unless you want to keep it to check one day!

Have a good day

**Comment by Ombrelin** [comment]
Hello,
Thank you for your kind words.
Sadly, we currently use an API listing current sessions on the server and this API can only be accessed by the server owner.

**Comment by radicalhashcan** [comment]
https://github.com/Arno500/plex-richpresence works just well for shared servers I'm sure you can update yours to do the same. Would be nice to be able to share what we're watching even if we the user aren't the owner of a plex server.

**Comment by Ombrelin** [comment]
Should be fixed in 2.0 version !
