### ISSUE TITLE
Failed to find any plex servers

### ISSUE THREAD

**Issue by WereTiger-ca** [Ombrelin/plex-rich-presence#42]
Was using the program in windows successfully.  Today I re-launched it and after authentication I got the error "Obtain Plex Server", "failed to find any plex servers".
In the same general timespan I upgraded Plex to version 1.22.2.4282 and started using Tautulli.  Not sure if one of those is related.

**Comment by Ombrelin** [comment]
Hello,
sorry to hear that. I just tested with my own PLEX setup, which is similar to yours (1.22.2.4282 and  Tautulli), but I wasn't able to reproduce the issue.

In order to provide help could you download the java version and run the app with the following command : 
```java
java -jar -Dlogging.level.root=DEBUG
```
 Reproduce the issue and post the debug log here.

**Comment by WereTiger-ca** [comment]
Sooo, I downloaded and installed Java from "https://www.java.com/en/download/", got version 8 update 281.  When I try to run the Jar file I get the following error:

C:\Users\Player 1\Downloads>java -jar -Dlogging.level.root=DEBUG plex-rich-presence-1.6.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: fr/arsenelapostolet/plexrichpresence/PlexRichPresenceApplication has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Is there another Java I'm not aware of?

**Comment by WereTiger-ca** [comment]
[PRP.log](https://github.com/Ombrelin/plex-rich-presence/files/6288134/PRP.log)

**Comment by Ombrelin** [comment]
Mmmh it looks like your server is detected but the tool can't connect to them.
@mclarence several month ago you mentioned a bug related to local loop blocking connection. Do you think this issue might be related ?

**Comment by WereTiger-ca** [comment]
Initially I was trying to run it from my gaming PC, but when it had issues I moved to running it on my Plex server.  The error existed in both cases.

**Comment by mclarence** [comment]
Try to manually specify the plex server's ip address and port in settings.

**Comment by Visual917** [comment]
I have the same issue. Maybe because it is a shared server?

**Comment by mclarence** [comment]
> I have the same issue. Maybe because it is a shared server?

You must own the plex server for it to work. The current plex API does not allow anyone else except the owner/admin to see the plex server's session list.

If you get the "fail to find plex server" issue, try manually specifying the plex server address and port in the settings.

**Comment by Visual917** [comment]
:( This sucks. Your programming is top level though! Love it!

**Comment by WereTiger-ca** [comment]
Specifying the address worked.  Any way to supply that info via command line argument, or have it cached/saved?

**Comment by mclarence** [comment]
If auto login is checked it will save that info.

**Comment by WereTiger-ca** [comment]
I could have sworn I had to re-enter the info last time I rebooted.
I just tested closing and re-launching and it worked flawlessly.  I'd test rebooting but that server takes damn near a quarter-hour to boot.

**Comment by heyjeay** [comment]
so does specifying the ip address of the shared server work?

**Comment by mclarence** [comment]
> so does specifying the ip address of the shared server work?

No. Plex API only allows the server's owner/admin to see the plex session list which is requried for this program to work.
