### ISSUE TITLE
Scoop package

### ISSUE THREAD

**Issue by SuperZoops** [Ombrelin/plex-rich-presence#45]
I would personally love to see the this packaged for scoop. 
https://github.com/lukesampson/scoop
Has over 13k stars, I'm sure it would bring in more people.

**Comment by Ombrelin** [comment]
Thank you for your input, I'll check this out

**Comment by Ombrelin** [comment]
Won't implement, as it is available for windows through winget : https://winget.run/pkg/Ombrelin/PlexRichPresence
