### ISSUE TITLE
Issue connections to Plex Media Server over HTTPS

### ISSUE THREAD

**Issue by eeeAAAkkk** [Ombrelin/plex-rich-presence#46]
I had to deactivate forced https because the tool connects through http. Any chance to use https?

![image](https://user-images.githubusercontent.com/1528269/116909572-acb18200-ac44-11eb-9699-dcc7c6c8bc6c.png)

**Comment by Ombrelin** [comment]
Hi, I just verified that the plex media server supports HTTPS calls, I does. I'll patch to issue the calls to the server over HTTPS.
Thank you for pointing it out !

**Comment by eeeAAAkkk** [comment]
thx
