### ISSUE TITLE
Login fails when not setting server manually

### ISSUE THREAD

**Issue by AaronWiora** [Ombrelin/plex-rich-presence#47]
I tried to login to plex but it failed with the following error messages:
![Error Message Number 1](https://user-images.githubusercontent.com/17088412/121077212-a7ad9880-c7d7-11eb-8bc7-654e4224abfc.png)
![Error Message Number 2](https://user-images.githubusercontent.com/17088412/121077223-aa0ff280-c7d7-11eb-85e6-6caca182fc75.png)
When setting the servers address and port manually it works.

If needed I can send a log but I don't know how to access it.

Plex Server Version 1.23.1.4528
Plex Rich Presence Version 1.6

**Comment by Ombrelin** [comment]
Hello,

looks like an error with the XML deserialization. 
You should be able to export the logs by opening the log window & clicking the export button at the top of it

**Comment by ssstankly** [comment]
I'm not getting the same error messages but same issue, works if I set manually. Auto-login returns the following:

```
21:16:58.286 [JavaFX-Launcher] INFO  o.s.b.SpringApplication - Starting application on DESKTOP-QGF2D6J with PID 15728 (C:\Users\xxxx\Downloads\plex-rich-presence-1.6.jar started by seanf in C:\Users\xxxx\Downloads)
21:16:58.297 [JavaFX-Launcher] INFO  o.s.b.SpringApplication - No active profile set, falling back to default profiles: default
21:17:00.032 [JavaFX-Launcher] INFO  o.s.b.SpringApplication - Started application in 2.191 seconds (JVM running for 3.433)
21:17:01.549 [RPC-Callback-Handler] INFO  f.a.p.v.MainViewModel - Connected to Discord RPC
21:17:01.755 [AWT-EventQueue-0] INFO  f.a.p.c.TrayIconController - Tray icon initialized
21:17:02.254 [JavaFX Application Thread] INFO  f.a.p.v.MainViewModel - Logging in
21:17:06.993 [RxIoScheduler-2] INFO  f.a.p.v.MainViewModel - Obtaining Plex servers...
21:17:07.367 [RxIoScheduler-2] ERROR f.a.p.v.MainViewModel - Obtain plex server failed : Failed to find any plex servers.
```

I don't seem to be able to get debug level logging either.  Used the below command:

`java -jar plex-rich-presence-1.6.jar -Dlogging.level.root=DEBUG`

Am I doing something wrong? (highly likely)

I use two plex servers, one on the device I'm running this program on, another on a raspberry pi. I'm the owner of both.

**Comment by Ombrelin** [comment]
Okay thank you both for your precise feedback.
I have little time this month to work on this project but I will next month.
Sorry for the inconvenience !

**Comment by ssstankly** [comment]
> Okay thank you both for your precise feedback.
> I have little time this month to work on this project but I will next month.
> Sorry for the inconvenience !

No apology necessary, appreciate the quick reply.

**Comment by Jaynator495** [comment]
I have a similar issue, but I instead get a problem with it fetching my plex servers, error below
```
[INFO] Obtaining Plex servers...
[INFO] Obtaining user info...
[INFO] Successfully logged in as: Jaynator495
[ERROR] Error getting sessions failed : Connection reset
```

**Comment by Ombrelin** [comment]
Looks like an error when connecting to your plex server, is it reachable from your machine ?

**Comment by Jaynator495** [comment]
> Looks like an error when connecting to your plex server, is it reachable from your machine ?

Yes, however I can only connect to either of my 2 plex servers on the same machine it's hosted on. If I specify any IP other than 127.0.0.1, it pops up with that error. This includes the local IP instead of localhost IP. Meanwhile I can open plex web to all of the IPs I entered just fine
