### ISSUE TITLE
Show Album Titles

### ISSUE THREAD

**Issue by s3anyboy** [Ombrelin/plex-rich-presence#60]
Would it be possible to display album titles in addition to artist and track?
Would also be nice if there was a way to customize whats shown (ex remove the time remaining)

Anyway thanks and good work

**Comment by Ombrelin** [comment]
Hello,
I'm planning to rewrite the app with better technologies in the upcoming month, I'll take your suggestion into account

**Comment by averyfollett** [comment]
Would love this feature! Hope it's still in the works

**Comment by Ombrelin** [comment]
Hello !
Thank you for your interest. The app is in a kind of stand by since my coursework and apprenticeship hog most of my time :'( 
My coursework ends in april, by then I'll have more free time and working on this app will be my top priority !
Sorry for the delay,
Happy holidays :)

**Comment by Ombrelin** [comment]
This use case will be covered by #43
