### ISSUE TITLE
Not showing media name

### ISSUE THREAD

**Issue by alexboutros** [Ombrelin/plex-rich-presence#61]
Running the latest version (Github releases says 1.7, but it installs 1.6). Discord just says playing Plex and a timer that doesn't seem to match up with what's playing.

**Comment by Ombrelin** [comment]
That's odd, I'll try to reproduce

**Comment by alexcomo95** [comment]
Duplicate of #58

**Comment by Ombrelin** [comment]
Closed as duplicate of #58
