### ISSUE TITLE
Weird display language

### ISSUE THREAD

**Issue by honzu** [Ombrelin/plex-rich-presence#62]
![image](https://user-images.githubusercontent.com/51051991/136666683-8a680502-0cbd-4370-b454-f61f435b38ef.png)
![image](https://user-images.githubusercontent.com/51051991/136666689-eaf2e44e-44bd-44cc-a739-8658c32e2106.png)

**Comment by Ombrelin** [comment]
Wow, weird indeed. What is your OS, and what is your language ?

**Comment by honzu** [comment]
I'm on Windows 11 22000.194
I have English, Vietnamese, Japanese and Chinese language packs installed but I have my display language set as English
![image](https://user-images.githubusercontent.com/51051991/136666901-ebf7e70c-f5bf-4f8d-aa27-6d3dffdc1d4c.png)

**Comment by Ombrelin** [comment]
Okay that's very strange, I have not switched to Windows 11 yet but I will investigate it.

**Comment by Ombrelin** [comment]
Okay it could be related to a font ne being present on the system but I don't remember using a specific font

**Comment by honzu** [comment]
> Okay it could be related to a font ne being present on the system but I don't remember using a specific font

I think it was due to some language-specific font messing it up. I tried resetting font settings and the display language is normal now.
