### ISSUE TITLE
[Enhancement] Add cover art/poster art to be displayed in RPC

### ISSUE THREAD

**Issue by Ravencentric** [Ombrelin/plex-rich-presence#70]
Discord added support for using links for RPC. Would be cool if it could be implemented.
could use TMDB for posters.
 
Example: https://github.com/PvtTyphoon/lfm-rich-presence

**Comment by itslino** [comment]
It's planned for version 2.0+ onward.
https://github.com/Ombrelin/plex-rich-presence/discussions/66
