### ISSUE TITLE
Wrong version number displayed

### ISSUE THREAD

**Issue by AaronWiora** [Ombrelin/plex-rich-presence#71]
I downloaded [plex-rich-presence-setup.exe](https://github.com/Ombrelin/plex-rich-presence/releases/download/v1.7/plex-rich-presence-setup.exe) version 1.**7** but the setup displays version 1.**6** ..
![Capture](https://user-images.githubusercontent.com/17088412/172045429-7c51fd37-ba6e-4148-aa32-0c1a7b14cbff.PNG)
...and so does the program after installing.
![Capture3](https://user-images.githubusercontent.com/17088412/172045580-bd18714f-1f1d-4eba-9777-4e16f3d788aa.PNG)

**Comment by Ombrelin** [comment]
Hello ! Thank you for reporting this issue. It should not impair the features of the app. It will be fixed with the 2.0 version which i'm working on.
