### ISSUE TITLE
open program

### ISSUE THREAD

**Issue by jauzin23** [Ombrelin/plex-rich-presence#72]
im sorry but i didnt understand how do i open the program?

**Comment by Ombrelin** [comment]
If you are on windows, use the installer, otherwise run the jar using `java -jar` command

**Comment by jauzin23** [comment]
> If you are on windows, use the installer, otherwise run the jar using `java -jar` command

where is the installer??

**Comment by Ombrelin** [comment]
You van download it from the release page

**Comment by jauzin23** [comment]
> You van download it from the release page

i alredy did.
i dont know where the file is.
https://jz3n.xyz/IAmALegend/v4n62vaw.png

**Comment by Ombrelin** [comment]
You downloaded the repository source. Here is the link to the release page where you can download the setup : https://github.com/Ombrelin/plex-rich-presence/releases

**Comment by jauzin23** [comment]
> You downloaded the repository source. Here is the link to the release page where you can download the setup : https://github.com/Ombrelin/plex-rich-presence/releases

ok thx, i got this error, how do i fix it??
https://jz3n.xyz/IAmALegend/t6xzkyke.png

**Comment by Ombrelin** [comment]
Do you have any Plex server linked to your Plex account ?

**Comment by jauzin23** [comment]
> Do you have any Plex server linked to your Plex account ?

https://jz3n.xyz/IAmALegend/2r20hkvk.png
i do

**Comment by Ombrelin** [comment]
Ha :/ sadly the app does only work for server admins for now :( This shortcoming will be fixed in the upcoming 2.0 version.
