### ISSUE TITLE
The destination file cannot be found in the installed folder.

### ISSUE THREAD

**Issue by bulletproof2k** [Ombrelin/plex-rich-presence#75]
After installing the program, a white icon without a logo. It does not start, throws an error.

**Comment by LarveyOfficial** [comment]
Same issue

**Comment by Ombrelin** [comment]
Hi, sorry to hear that. Are you guys on windows ?

**Comment by bulletproof2k** [comment]
Yep.

**Comment by Ombrelin** [comment]
There where an issue with the windows installer ; should be fixed in the last release

**Comment by bulletproof2k** [comment]
Can the latest version be installed on top of the previous version, or is it better to remove the old version before installing?

**Comment by Ombrelin** [comment]
Since it regards the shortcut registered with windows, I believe it's safer to remove last version and then install the new one.

**Comment by bulletproof2k** [comment]
Ok, thx.

**Comment by Ombrelin** [comment]
Should be fixed in last release, please re-open if still having this issue
