### ISSUE TITLE
Just shows up as: Plex - Idle ( while watching movies )

### ISSUE THREAD

**Issue by heartdeadz** [Ombrelin/plex-rich-presence#81]
I just installed this new version, and i just realised that no matter what movie i play, it just shows up as: Idle ( on discord.)

i've uninstalled,  but to no avail! ( adding a screenshot )
![i5r6ljNMST](https://user-images.githubusercontent.com/97589437/197287684-460e3035-ba99-4e9b-912e-8ad98f42748a.png)

so i found my old 1.6  files, and i tried that one instead, and it instantly worked! :D 
wondering if you might have an idea to what it might be? 
adding a 1.6 screenshot too
![SoyeSbFN6Y](https://user-images.githubusercontent.com/97589437/197288021-e276f5e1-ffed-43e1-8972-5676606b9d4b.png)

**Comment by Ombrelin** [comment]
Please provide `logs.txt` from the `.plexrichpresence` folder of your home directory

**Comment by heartdeadz** [comment]
> Please provide `logs.txt` from the `.plexrichpresence` folder of your home directory

hey there! 1rst of all, sorry for making two exact same posts, i have no idea how that empty one came in before this one got posted, but ):

here's the log file! hopefully its the correct one: 
[logs.txt](https://github.com/Ombrelin/plex-rich-presence/files/9842504/logs.txt)

**Comment by Ombrelin** [comment]
Hi ! Thanks to your bug I could track the bug and reproduce it, I'm working on a fix.

**Comment by heartdeadz** [comment]
> Hi ! Thanks to your logs I could track the bug and reproduce it, I'm working on a fix.

That is absolutely fantastic! :D i'll just keep using 1.6 until that is sorted then!
tysm for your fantastic tool! :D

**Comment by Ombrelin** [comment]
Fixed in last release.

**Comment by heartdeadz** [comment]
hell yea! this worked!  thank you so much man! :D i can get rid of 1.6 now!
