### ISSUE TITLE
Option to disable "Idle" status

### ISSUE THREAD

**Issue by totaltentigers** [Ombrelin/plex-rich-presence#84]
This is just a feature request!

I would like the ability to disable the "Idle" status with v2.0. I noticed the "Idle" status overrides any other games/apps displaying their activity on Discord.

**Comment by Ombrelin** [comment]
Wouldn't closing the app when you do not use it cover this use case ?

**Comment by totaltentigers** [comment]
I am not sure how others typically use this software, but I normally leave it running at all times. I do not want to close and reopen this software every time I start and stop using Plex, so that is why I prefer to leave it always running.

**Comment by Ombrelin** [comment]
Ok ok, will look into it then

**Comment by heartdeadz** [comment]
just to show that others want it too, i'd love to just always keep this app running! :D  instead of re-booting it everytime i wanna watch a show/movie.

same with being able to X it out, without the app terminating itself :D

**Comment by Ombrelin** [comment]
implemented in last version
