### ISSUE TITLE
option to  click the x, but actually hide the program in taskbar 

### ISSUE THREAD

**Issue by PsychoManiac189** [Ombrelin/plex-rich-presence#85]
if i click the x it closes the program. id like it to hide it in taskbar like the old 1.6 version did

**Comment by heartdeadz** [comment]
This! 100%, its been annoying me too!

**Comment by ippeppe** [comment]
Please this times 100.

**Comment by Ombrelin** [comment]
Will work on this issue next weekend, since it seems very much in demand

**Comment by seriosbrad** [comment]
> Will work on this issue next weekend, since it seems very much in demand

Sweet.  The option to start up automatically start minimized to the tray would be a great addition too.

**Comment by Brittle73** [comment]
+1: minimize to sys tray would be ideal. Trying to find a native way to do it, but it looks like I would need third party apps. This would definitely be a useful feature! Neat app, very easy to install!

**Comment by Brittle73** [comment]
> +1: minimize to sys tray would be ideal. Trying to find a native way to do it, but it looks like I would need third party apps. This would definitely be a useful feature! Neat app, very easy to install!

Oops, meant to add... I'm not sure if I want to run this at startup, but adding that option inside the app would be cool too. I added it to shell:startup on my work PC, but haven't gotten to test it yet.

**Comment by Ombrelin** [comment]
Hi : Glad you enjoy the app
Too clarify : minimize to tray IS currently supported, but you have to click the tray icon to do it.
What is not yet implemented is reducing to tray when clicking the "close" button on the app system.

**Comment by Ombrelin** [comment]
implemented in last version
