### ISSUE TITLE
Enhancement suggestion: swap tv show name/title

### ISSUE THREAD

**Issue by heartdeadz** [Ombrelin/plex-rich-presence#86]
not that its a big deal or anything, but swapping the tv show name + episode name around would be nice! as it is now, its:

Episode name
TV show name
Time remaining/played.
![wqxZP08CJB](https://user-images.githubusercontent.com/97589437/199476157-9aab5607-c73f-480c-9e2d-dbd097e43e09.png)
-------------------------------------
it would be fantastic if we could turn that around to:
TV show name.
Episode name.
Time remaining/played.
------------

(taking that screenshot into mind, it would be way neater to have it say:)

The Devil's Hour.

33.3
Time:remaining.

it just shows up really weird while playing stuff on plex.
or just a option to toggle the two! :D

**Comment by Ombrelin** [comment]
This use case should be coveree by #43
