### ISSUE TITLE
Application crashes when trying to switch server

### ISSUE THREAD

**Issue by jensengillett** [Ombrelin/plex-rich-presence#90]
I genuinely don't know what's going on here. When I open the application, it fails to connect to the server, then clicking the 'change server' button crashes the app entirely. 

I tried uninstalling and reinstalling already and that didn't help. Using the latest release version (2.0.7) on Windows 10.

Of note: my Plex account has two servers connected to it (one local, one remote). 

I don't see any debug logs or anything in the program files folder where the app is installed, and there isn't anything in %appdata% as far as I can find, so I'm kind of at a loss for what to do here.

See video of the problem below:

https://user-images.githubusercontent.com/62229586/212527945-dcd5e25c-cf7b-442a-8d19-0378cad7eeb1.mp4

**Comment by Ombrelin** [comment]
Hi, sorry to hear that.
Logs should be in a `.plexrichpresence` folder in your user directory.

**Comment by jensengillett** [comment]
[logs2023011423.txt](https://github.com/Ombrelin/plex-rich-presence/files/10421366/logs2023011423.txt)
Here's the latest log in that folder. I'm also guessing maybe it has something to do with the storedData.json file not being cleared on an uninstall? I'm going to try renaming that and letting it create a new one to see if that helps.

**Comment by jensengillett** [comment]
That did fix the crash - I'm guessing the old token was invalid and for some reason that crashed the application. Oddly enough I'm still not able to get it to connect to either of the servers though - it just complains about being unable to connect to them, and using the private IP address of one of them instead connects but it never detects anything playing on either the main user or managed user account.

**Comment by Ombrelin** [comment]
Thank you for your feedback, indeed that's what seems to have happened. I'll implement a system to prompt for new login when that happens !

**Comment by Ombrelin** [comment]
Fixed in last release
