### ISSUE TITLE
command line flag to start minimized

### ISSUE THREAD

**Issue by XenHat** [Ombrelin/plex-rich-presence#91]
I would like the option to start the program minimized.

The standard flag name `--minimized` would be appreciated.

Use case: Putting a shortcut to it in my autostart folder:
![image](https://user-images.githubusercontent.com/980408/213844835-b769112f-30f7-473e-b936-a2803cad6822.png)

**Comment by Ombrelin** [comment]
Should be straightforward to implement, thank you for the suggestion

**Comment by Ombrelin** [comment]
Implemented in last release
