### ISSUE TITLE
Crashes on track change

### ISSUE THREAD

**Issue by OpNop** [Ombrelin/plex-rich-presence#98]
Just playing music and it shows up in Discord, but after the track ends and goes to the next one the app crashes silently

**Comment by Ombrelin** [comment]
Thanks for the feedback, I'll investigate

**Comment by Ombrelin** [comment]
Was able to reproduce and fix issue, patched in last release.
Thanks again for your feedback.

**Comment by OpNop** [comment]
Confirmed, latest version fixed it, thanks again!
